[MAIN]

DEBUG =  true
ADMINS= [['zoumi','xxxxx@xxx.com'],]
HTTP = true
HTTPS = false
DOMAIN = '127.0.0.1'

#Local time zone for this installation. Choices can be found here:
#http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
#although not all choices may be available on all operating systems.
#In a Windows environment this must be set to your system time zone.
TIME_ZONE = 'Africa/Abidjan'
#Language code for this installation. All choices can be found here:
#http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = 'en-AU'
SITE_ID = 1



#If you set this to False, Django will make some optimizations so as not
#to load the internationalization machinery.
USE_I18N =  true

#If you set this to False, Django will not format dates, numbers and
#calendars according to the current locale.
USE_L10N =  true

#If you set this to False, Django will not use timezone-aware datetimes.
USE_TZ =  true

#Absolute filesystem path to the directory that will hold user-uploaded files.
#Example: "/var/www/example.com/media/"
MEDIA_ROOT='./'

#URL that handles the media served from MEDIA_ROOT. Make sure to use a
#trailing slash.
#Examples: "http://example.com/media/", "http://media.example.com/"
MEDIA_URL = '/media/'



#Absolute path to the directory static files should be collected to.
#Do not put anything in this directory yourself; store your static files
#in  "static/" subdirectories and in STATICFILES_DIRS.
#Example: "/var/www/example.com/static/"
STATIC_ROOT = './static'


#URL prefix for static files.
#Example: "http://example.com/static/", "http://static.example.com/"
STATIC_URL = '/static/'

#Make this unique, and do not share it with anybody.
SECRET_KEY = 'xxagdlcsagsaxxdsahfgdsafasxgasdxxr&j0vni'

[DATABASE]
USER='zoumi'
PASSWORD='11111111'
HOST='127.0.0.1'
PORT=3306
STORAGE_ENGINE='MYISAM'
